version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-dental}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-dental_db}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - backend

  app:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - ENVIRONMENT=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      - REQUIRE_REDIS=true
      - CACHE_ENABLED=true
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
    driver: bridge
