"""auto migration

Revision ID: 8b46ba6881ea
Revises: b59ee32519a8
Create Date: 2025-12-06 18:44:53.771657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b46ba6881ea'
down_revision: Union[str, Sequence[str], None] = 'b59ee32519a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('is_urgent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'is_urgent')
    # ### end Alembic commands ###
