"""treatment model

Revision ID: c392fcd4ce14
Revises: bb6e604cc9ca
Create Date: 2025-11-27 01:44:40.667485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c392fcd4ce14'
down_revision: Union[str, Sequence[str], None] = 'bb6e604cc9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatments', sa.Column('estimated_completion_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatments', 'estimated_completion_date')
    # ### end Alembic commands ###
